[project]
name = "paconvert"
version = "1.0.0"
authors = [
    {name="PaddlePaddle", email="Paddle-better@baidu.com"},
]
description = "PaddlePaddle Code Convert Toolkits"
readme = "README.md"
requires-python = ">=3.8"

[project.urls]
"Homepage" = "https://github.com/PaddlePaddle/PaConvert"
