# Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import textwrap

from apibase import APIBase

obj = APIBase("torch.distributions.IndependentTransform")


def test_case_1():
    pytorch_code = textwrap.dedent(
        """
        import torch
        multi_exp = torch.distributions.IndependentTransform(torch.distributions.Transform(), 1)
        result = multi_exp.forward_shape([1, 2])
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_2():
    pytorch_code = textwrap.dedent(
        """
        import torch
        multi_exp = torch.distributions.IndependentTransform(torch.distributions.SoftmaxTransform(), 2)
        result = multi_exp.forward_shape([1, 2])
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_3():
    pytorch_code = textwrap.dedent(
        """
        import torch
        multi_exp = torch.distributions.IndependentTransform(torch.distributions.SoftmaxTransform(), 2)
        result = multi_exp.forward_shape([1, 2, 3])
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_4():
    pytorch_code = textwrap.dedent(
        """
        import torch
        multi_exp = torch.distributions.IndependentTransform(torch.distributions.SoftmaxTransform(), 2, cache_size=1)
        result = multi_exp.forward_shape([1, 2, 3])
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_4
def test_case_5():
    pytorch_code = textwrap.dedent(
        """
        import torch
        multi_exp = torch.distributions.IndependentTransform(torch.distributions.SoftmaxTransform(), 2, 1)
        result = multi_exp.forward_shape([1, 2, 3])
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_4
def test_case_6():
    pytorch_code = textwrap.dedent(
        """
        import torch
        multi_exp = torch.distributions.IndependentTransform(base_transform=torch.distributions.SoftmaxTransform(), reinterpreted_batch_ndims=2, cache_size=1)
        result = multi_exp.forward_shape([1, 2, 3])
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_4
def test_case_7():
    pytorch_code = textwrap.dedent(
        """
        import torch
        multi_exp = torch.distributions.IndependentTransform(cache_size=1, reinterpreted_batch_ndims=2, base_transform=torch.distributions.SoftmaxTransform())
        result = multi_exp.forward_shape([1, 2, 3])
        """
    )
    obj.run(pytorch_code, ["result"])
