# Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import textwrap

import paddle
import pytest
from apibase import APIBase

obj = APIBase("torch.randint")


def test_case_1():
    pytorch_code = textwrap.dedent(
        """
        import torch
        result = torch.randint(3, 5, (3,))
        """
    )
    obj.run(pytorch_code, ["result"], check_value=False)


def test_case_2():
    pytorch_code = textwrap.dedent(
        """
        import torch
        result = torch.randint(10, (2, 2))
        """
    )
    obj.run(pytorch_code, ["result"], check_value=False)


def test_case_3():
    pytorch_code = textwrap.dedent(
        """
        import torch
        result = torch.randint(3, 10, (2, 2), dtype=torch.int32, requires_grad=False)
        """
    )
    obj.run(pytorch_code, ["result"], check_value=False)


def test_case_4():
    pytorch_code = textwrap.dedent(
        """
        import torch
        result = torch.randint(3, 10, (2, 2), dtype=torch.int32)
        """
    )
    obj.run(pytorch_code, ["result"], check_value=False)


def test_case_5():
    pytorch_code = textwrap.dedent(
        """
        import torch
        out = torch.empty(2, 2, dtype=torch.int32)
        result = torch.randint(3, 10, (2, 2), out=out, dtype=torch.int32, layout=torch.strided, device=torch.device('cpu'), pin_memory=False, requires_grad=False)
        """
    )
    obj.run(pytorch_code, ["result"], check_value=False)


def test_case_6():
    pytorch_code = textwrap.dedent(
        """
        import torch
        flag = False
        result = torch.randint(3, 10, (2, 2), dtype=torch.int64, requires_grad=flag)
        """
    )
    obj.run(pytorch_code, ["result"], check_value=False)


def test_case_7():
    pytorch_code = textwrap.dedent(
        """
        import torch
        result = torch.randint(3, 10, (2, 2), generator=None, dtype=torch.int64, layout=torch.strided, device=torch.device('cpu'), pin_memory=False, requires_grad=False)
        """
    )
    obj.run(pytorch_code, ["result"], check_value=False)


# generated by validate_unittest autofix, based on test_case_7
def test_case_8():
    pytorch_code = textwrap.dedent(
        """
        import torch
        out = torch.empty(2, 2, dtype=torch.int32)
        result = torch.randint(low=3, high=10, size=(2, 2), generator=None, out=out, dtype=torch.int32, layout=torch.strided, device=torch.device('cpu'), pin_memory=False)
        """
    )
    obj.run(pytorch_code, ["result"], check_value=False)


# generated by validate_unittest autofix, based on test_case_7
def test_case_9():
    pytorch_code = textwrap.dedent(
        """
        import torch
        out = torch.empty(2, 2, dtype=torch.int32)
        result = torch.randint(requires_grad=False, pin_memory=False, device=torch.device('cpu'), layout=torch.strided, dtype=torch.int32, out=out, generator=None, size=(2, 2), high=10, low=3)
        """
    )
    obj.run(pytorch_code, ["result"], check_value=False)


def test_case_10():
    pytorch_code = textwrap.dedent(
        """
        import torch
        high = 10
        size = (2, 2)
        result = torch.randint(high, size)
        """
    )
    obj.run(pytorch_code, ["result"], check_value=False)


def test_case_11():
    pytorch_code = textwrap.dedent(
        """
        import torch
        high = 10
        size = (2, 2)
        result = torch.randint(high, size=size)
        """
    )
    obj.run(pytorch_code, ["result"], check_value=False)


@pytest.mark.skipif(
    condition=not paddle.device.is_compiled_with_cuda(),
    reason="can only run on paddle with CUDA",
)
def test_case_12():
    pytorch_code = textwrap.dedent(
        """
        import torch
        high = 10
        size = (2, 2)
        result = torch.randint(high=high, size=size, generator=None, dtype=torch.int64, layout=torch.strided, device=torch.device('cpu'), pin_memory=True)
        """
    )
    obj.run(pytorch_code, ["result"], check_value=False)
