# Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import textwrap

from apibase import APIBase

obj = APIBase("torch.divide")


# paddle not support input python number, x/y must be Tensor
# def test_case_1():
#     pytorch_code = textwrap.dedent(
#         """
#         import torch
#         a = torch.tensor([ 0.5950,-0.0872, 2.3298, -0.2972])
#         result = torch.divide(a, 0.5)
#         """
#     )
#     obj.run(pytorch_code, ["result"])


def test_case_2():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([[ 0.5950,-0.0872], [2.3298, -0.2972]])
        b = torch.tensor([0.1815, -1.0111])
        result = torch.divide(a, b)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_3():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([[ 0.5950,-0.0872], [2.3298, -0.2972]])
        b = torch.tensor([0.1815, -1.0111])
        result = torch.divide(input=a, other=b)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_4():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([[ 0.5950,-0.0872], [2.3298, -0.2972]])
        b = torch.tensor([0.1815, -1.0111])
        result = torch.divide(input=a, other=b, rounding_mode=None)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_5():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([[ 0.5950,-0.0872], [2.3298, -0.2972]])
        b = torch.tensor([0.1815, -1.0111])
        result = torch.divide(input=a, other=b, rounding_mode="trunc")
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_6():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([[ 0.5950,-0.0872], [2.3298, -0.2972]])
        b = torch.tensor([0.1815, -1.0111])
        result = torch.divide(input=a, other=b, rounding_mode="floor")
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_7():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([[ 0.5950,-0.0872], [2.3298, -0.2972]])
        b = torch.tensor([0.1815, -1.0111])
        out = torch.tensor([[ 0.5950,-0.0872], [2.3298, -0.2972]])
        result = torch.divide(input=a, other=b, rounding_mode="floor", out=out)
        """
    )
    obj.run(pytorch_code, ["out"])


def test_case_8():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([[4, 9, 8]])
        b = torch.tensor([2, 3, 4])
        result = torch.divide(input=a, other=b)
        """
    )
    obj.run(pytorch_code, ["result"])


# current type promotion only support calculations between floating-point numbers and between complex and real numbers
# def _test_case_9():
#     pytorch_code = textwrap.dedent(
#         """
#         import torch
#         a = torch.tensor([[4., 9., 8.]])
#         b = torch.tensor([2, 3, 4])
#         result = torch.divide(input=a, other=b)
#         """
#     )
#     obj.run(pytorch_code, ["result"])


def _test_case_10():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([[4, 3, 8]])
        b = torch.tensor([3, 2, 5])
        result = torch.divide(input=a, other=b)
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_7
def test_case_11():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([[ 0.5950,-0.0872], [2.3298, -0.2972]])
        b = torch.tensor([0.1815, -1.0111])
        out = torch.tensor([[ 0.5950,-0.0872], [2.3298, -0.2972]])
        result = torch.divide(out=out, rounding_mode="floor", other=b, input=a)
        """
    )
    obj.run(pytorch_code, ["out"])


def test_case_12():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([[4, 9, 8]], dtype=torch.float32)
        b = torch.tensor([2, 3, 4], dtype=torch.float64)
        result = torch.divide(input=a, other=b)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_13():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([[4, 9, 8]], dtype=torch.float16)
        b = torch.tensor([2, 3, 4], dtype=torch.float64)
        result = torch.divide(input=a, other=b)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_14():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([[4, 9, 8]], dtype=torch.float32)
        b = torch.tensor([2, 3, 4], dtype=torch.float16)
        result = torch.divide(input=a, other=b)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_15():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([[4, 9, 8]], dtype=torch.float32)
        b = torch.tensor([2, 3, 4], dtype=torch.complex64)
        result = torch.divide(input=a, other=b)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_16():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([[4, 9, 8]], dtype=torch.int32)
        b = torch.tensor([2, 3, 4], dtype=torch.complex64)
        result = torch.divide(input=a, other=b)
        """
    )
    obj.run(pytorch_code, ["result"])
