# Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import textwrap

from apibase import APIBase

obj = APIBase("torch.kthvalue")


def test_case_1():
    pytorch_code = textwrap.dedent(
        """
        import torch
        x = torch.tensor([1., 2., 3., 4., 5.])
        result = torch.kthvalue(x, 4)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_2():
    pytorch_code = textwrap.dedent(
        """
        import torch
        x = torch.tensor([[ 1., 2., 3.], [ 4., 5., 6.]])
        result = torch.kthvalue(x, 2, 0, True)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_3():
    pytorch_code = textwrap.dedent(
        """
        import torch
        x = torch.tensor([[ 1., 2., 3.], [ 4., 5., 6.]])
        result = torch.kthvalue(x, k=2, dim=0, keepdim=True)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_4():
    pytorch_code = textwrap.dedent(
        """
        import torch
        x = torch.tensor([[ 1., 2., 3.], [ 4., 5., 6.]])
        result = torch.kthvalue(x, k=2, dim=0, keepdim=True)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_5():
    pytorch_code = textwrap.dedent(
        """
        import torch
        x = torch.tensor([[ 1., 2., 3.], [ 4., 5., 6.]])
        out = (torch.randn(1, 3), torch.tensor(1))
        result = torch.kthvalue(x, k=2, dim=0, keepdim=True, out=out)
        """
    )
    obj.run(pytorch_code, ["result", "out"])


# generated by validate_unittest autofix, based on test_case_5
def test_case_6():
    pytorch_code = textwrap.dedent(
        """
        import torch
        x = torch.tensor([[ 1., 2., 3.], [ 4., 5., 6.]])
        out = (torch.randn(1, 3), torch.tensor(1))
        result = torch.kthvalue(input=x, k=2, dim=0, keepdim=True, out=out)
        """
    )
    obj.run(pytorch_code, ["result", "out"])


# generated by validate_unittest autofix, based on test_case_5
def test_case_7():
    pytorch_code = textwrap.dedent(
        """
        import torch
        x = torch.tensor([[ 1., 2., 3.], [ 4., 5., 6.]])
        out = (torch.randn(1, 3), torch.tensor(1))
        result = torch.kthvalue(out=out, keepdim=True, dim=0, k=2, input=x)
        """
    )
    obj.run(pytorch_code, ["result", "out"])
