# Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import textwrap

from apibase import APIBase

obj = APIBase("torch.set_printoptions")


def test_case_1():
    pytorch_code = textwrap.dedent(
        """
        import torch
        torch.set_printoptions(precision=2)
        """
    )
    obj.run(pytorch_code)


def test_case_2():
    pytorch_code = textwrap.dedent(
        """
        import torch
        torch.set_printoptions()
        """
    )
    obj.run(pytorch_code)


def test_case_3():
    pytorch_code = textwrap.dedent(
        """
        import torch
        torch.set_printoptions(precision=8, threshold=2000, edgeitems=4, linewidth=100, profile='full')
        """
    )
    obj.run(pytorch_code)


def test_case_4():
    pytorch_code = textwrap.dedent(
        """
        import torch
        torch.set_printoptions(precision=8, threshold=2000, edgeitems=4, linewidth=100, profile='full', sci_mode=False)
        """
    )
    obj.run(pytorch_code)


# generated by validate_unittest autofix, based on test_case_4
def test_case_5():
    pytorch_code = textwrap.dedent(
        """
        import torch
        torch.set_printoptions(8, 2000, 4, 100, 'full', False)
        """
    )
    obj.run(pytorch_code)


# generated by validate_unittest autofix, based on test_case_4
def test_case_6():
    pytorch_code = textwrap.dedent(
        """
        import torch
        torch.set_printoptions(sci_mode=False, profile='full', linewidth=100, edgeitems=4, threshold=2000, precision=8)
        """
    )
    obj.run(pytorch_code)
