# Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
import textwrap

from apibase import APIBase

obj = APIBase("torch.ldexp")


def test_case_1():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([1., 2., -3., -4., 5.])
        b = torch.tensor([1., 2., -3., -4., 5.])
        result = torch.ldexp(a, b)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_2():
    pytorch_code = textwrap.dedent(
        """
        import torch
        result = torch.ldexp(input=torch.tensor([1., 2., -3., -4., 5.]), other=torch.tensor([1., 2., -3., -4., 5.]))
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_3():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([1., 2., -3., -4., 5.])
        out = torch.tensor([1., 2., -3., -4., 5.])
        result = torch.ldexp(a, a, out=out)
        """
    )
    obj.run(pytorch_code, ["out"])


def test_case_4():
    pytorch_code = textwrap.dedent(
        """
        import torch
        result = torch.ldexp(torch.tensor([1.]),torch.tensor([1., 2., -3., -4., 5.]))
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_5():
    pytorch_code = textwrap.dedent(
        """
        import torch
        result = torch.ldexp(torch.tensor([1.]), torch.tensor([1, 2, -3, -4, 5]))
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_3
def test_case_6():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([1., 2., -3., -4., 5.])
        out = torch.tensor([1., 2., -3., -4., 5.])
        result = torch.ldexp(input=a, other=a, out=out)
        """
    )
    obj.run(pytorch_code, ["out"])


# generated by validate_unittest autofix, based on test_case_3
def test_case_7():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([1., 2., -3., -4., 5.])
        out = torch.tensor([1., 2., -3., -4., 5.])
        result = torch.ldexp(out=out, other=a, input=a)
        """
    )
    obj.run(pytorch_code, ["out"])


def test_case_8():
    """Test with out parameter as keyword argument"""
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([1., 2., 3.])
        b = torch.tensor([1, 2, 3])
        out = torch.zeros_like(a)
        torch.ldexp(input=a, other=b, out=out)
        result = out
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_9():
    """Test with different tensor shapes (broadcasting)"""
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([[1., 2.], [3., 4.]])
        b = torch.tensor([1, 2])
        result = torch.ldexp(a, b)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_10():
    """Test with float64 dtype"""
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([1.0, 2.0], dtype=torch.float64)
        b = torch.tensor([1, 2], dtype=torch.int64)
        result = torch.ldexp(a, b)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_11():
    """Test with negative exponent"""
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([1., 2., 4.])
        b = torch.tensor([-1, -2, -3])
        result = torch.ldexp(a, b)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_12():
    """Test with zero exponent"""
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([1., 2., 3.])
        b = torch.tensor([0, 0, 0])
        result = torch.ldexp(a, b)
        """
    )
    obj.run(pytorch_code, ["result"])
