# Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

import textwrap

from apibase import APIBase

obj = APIBase("torch.polygamma")


def test_case_1():
    pytorch_code = textwrap.dedent(
        """
        import torch
        result = torch.polygamma(1, torch.tensor([1, 0.5]))
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_2():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([1, 0.5])
        result = torch.polygamma(1, a)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_3():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = [1, 0.5]
        out = torch.tensor(a)
        result = torch.polygamma(1, torch.tensor(a), out=out)
        """
    )
    obj.run(pytorch_code, ["result", "out"])


# generated by validate_unittest autofix, based on test_case_3
def test_case_4():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = [1, 0.5]
        out = torch.tensor(a)
        result = torch.polygamma(n=1, input=torch.tensor(a), out=out)
        """
    )
    obj.run(pytorch_code, ["result", "out"])


# generated by validate_unittest autofix, based on test_case_3
def test_case_5():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = [1, 0.5]
        out = torch.tensor(a)
        result = torch.polygamma(out=out, input=torch.tensor(a), n=1)
        """
    )
    obj.run(pytorch_code, ["result", "out"])
