# Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import textwrap

import pytest
from apibase import APIBase

obj = APIBase("torch.nn.LayerNorm")


def test_case_1():
    pytorch_code = textwrap.dedent(
        """
        import torch.nn as nn
        import torch
        m = nn.LayerNorm(10)
        input = torch.ones(2, 5, 10)
        result = m(input)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_2():
    pytorch_code = textwrap.dedent(
        """
        import torch.nn as nn
        import torch
        m = nn.LayerNorm([5,10,10])
        input = torch.ones(2, 5, 10, 10)
        result = m(input)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_3():
    pytorch_code = textwrap.dedent(
        """
        import torch.nn as nn
        import torch
        m = nn.LayerNorm(10, elementwise_affine=True)
        input = torch.ones(2, 5, 10)
        result = m(input)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_4():
    pytorch_code = textwrap.dedent(
        """
        import torch.nn as nn
        import torch
        m = nn.LayerNorm(10, dtype=torch.float32)
        input = torch.ones(2, 5, 10)
        result = m(input)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_5():
    pytorch_code = textwrap.dedent(
        """
        import torch.nn as nn
        import torch
        m = nn.LayerNorm(10, elementwise_affine=False, dtype=torch.float32)
        input = torch.ones(2, 5, 10)
        result = m(input)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_6():
    pytorch_code = textwrap.dedent(
        """
        import torch.nn as nn
        import torch
        m = nn.LayerNorm(10, elementwise_affine=False, dtype=torch.float32, eps=1e-05, device="cpu")
        input = torch.ones(2, 5, 10)
        result = m(input)
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_6
@pytest.mark.skip(reason="some params are only supported as kwargs")
def test_case_7():
    pytorch_code = textwrap.dedent(
        """
        import torch.nn as nn
        import torch
        m = nn.LayerNorm(10, 1e-05, False, "cpu", torch.float32)
        input = torch.ones(2, 5, 10)
        result = m(input)
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_6
def test_case_8():
    pytorch_code = textwrap.dedent(
        """
        import torch.nn as nn
        import torch
        m = nn.LayerNorm(normalized_shape=10, eps=1e-05, elementwise_affine=False, device="cpu", dtype=torch.float32)
        input = torch.ones(2, 5, 10)
        result = m(input)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_9():
    pytorch_code = textwrap.dedent(
        """
        import torch.nn as nn
        import torch
        m = nn.LayerNorm(device="cpu", dtype=torch.float32, normalized_shape=10, eps=1e-05, elementwise_affine=False)
        input = torch.ones(2, 5, 10)
        result = m(input)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_10():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        input = torch.arange(60, dtype=torch.float32).reshape(2, 3, 10) / 7.0 - 2.0
        m = nn.LayerNorm(10, eps=1e-04, elementwise_affine=True, bias=False, dtype=torch.float32)
        result = m(input)
        """
    )
    obj.run(pytorch_code, ["result"], rtol=2e-5, atol=1e-7)


def test_case_11():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        input = torch.arange(24, dtype=torch.float64).reshape(2, 3, 4) / 5.0 + 0.3
        m = nn.LayerNorm(4, eps=1e-04, elementwise_affine=False, bias=False, dtype=torch.float64)
        result = m(input)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_12():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        args = (6, 1e-04, True, True, "cpu", torch.float32)
        m = nn.LayerNorm(*args)
        input = torch.arange(12, dtype=torch.float32).reshape(2, 6) / 3.0 - 1.0
        result = m(input)
        """
    )
    obj.run(pytorch_code, ["result"], rtol=2e-5, atol=1e-7)


def test_case_13():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        input = torch.arange(48, dtype=torch.float32).reshape(2, 2, 3, 4) / 9.0 + 1.0
        m = nn.LayerNorm(
            device="cpu",
            bias=False,
            elementwise_affine=True,
            dtype=torch.float32,
            eps=1e-04,
            normalized_shape=(3, 4),
        )
        result = m(input)
        """
    )
    obj.run(pytorch_code, ["result"], rtol=3e-5, atol=1e-7)


def test_case_14():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        normalized_shape = 5
        eps = 1e-04
        kwargs = {
            "elementwise_affine": False,
            "bias": False,
            "device": "cpu",
            "dtype": torch.float64,
        }
        m = nn.LayerNorm(normalized_shape, eps, **kwargs)
        input = torch.linspace(-2.5, 3.5, steps=20, dtype=torch.float64).reshape(2, 2, 5)
        result = m(input)
        """
    )
    obj.run(pytorch_code, ["result"], rtol=1e-5, atol=1e-6)
