# Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
import textwrap

from apibase import APIBase

obj = APIBase("torch.hypot")


def test_case_1():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([1., 2, 3])
        b = torch.tensor([4., 5, 6])
        result = torch.hypot(a, b)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_2():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([1.])
        b = torch.tensor([4., 5, 6])
        result = torch.hypot(input=a, other=b)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_3():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([1., 2, 3])
        b = torch.tensor([4., 5, 6])
        out = torch.tensor([4., 5, 6])
        result = torch.hypot(other=b, input=a, out=out)
        """
    )
    obj.run(pytorch_code, ["out"])


def test_case_4():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([1., 2, 3])
        b = torch.tensor([4., 5, 6])
        out = torch.tensor([4., 5, 6])
        result = torch.hypot(input=a, other=b+1, out=out)
        """
    )
    obj.run(pytorch_code, ["result", "out"])


# generated by validate_unittest autofix, based on test_case_3
def test_case_5():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([1., 2, 3])
        b = torch.tensor([4., 5, 6])
        out = torch.tensor([4., 5, 6])
        result = torch.hypot(out=out, other=b, input=a)
        """
    )
    obj.run(pytorch_code, ["out"])


# generated by validate_unittest autofix, based on test_case_4
def test_case_6():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([1., 2, 3])
        b = torch.tensor([4., 5, 6])
        out = torch.tensor([4., 5, 6])
        result = torch.hypot(out=out, other=b+1, input=a)
        """
    )
    obj.run(pytorch_code, ["result", "out"])


def test_case_7():
    pytorch_code = textwrap.dedent(
        """
        import torch
        x = torch.tensor([[3.0, 5.0], [8.0, 12.0]])
        y = torch.tensor([4.0, 12.0])
        args = (x, y)
        result = torch.hypot(*args)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_8():
    pytorch_code = textwrap.dedent(
        """
        import torch
        x = torch.tensor([[3.0, 5.0], [8.0, 12.0]], dtype=torch.float32)
        y = torch.tensor([[4.0, 12.0], [15.0, 16.0]], dtype=torch.float32)
        result = torch.hypot(other=y, input=x)
        """
    )
    obj.run(pytorch_code, ["result"])
