# Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import textwrap

from apibase import APIBase

obj = APIBase("torch.nn.Linear")


def test_case_1():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        x = torch.randn(1, 2, 10)
        model = nn.Linear(10, 20)
        result = model(x)
        """
    )
    obj.run(pytorch_code, ["result"], check_value=False)


def test_case_2():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        x = torch.randn(1, 2, 10)
        model = nn.Linear(10, 20, bias=True)
        result = model(x)
        """
    )
    obj.run(pytorch_code, ["result"], check_value=False)


def test_case_3():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        x = torch.randn(1, 2, 10)
        model = nn.Linear(in_features=10, out_features=20, bias=True)
        result = model(x)
        """
    )
    obj.run(pytorch_code, ["result"], check_value=False)


def test_case_4():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        x = torch.randn(1, 2, 10)
        model = nn.Linear(in_features=10, out_features=20, bias=True, dtype=torch.float32)
        result = model(x)
        """
    )
    obj.run(pytorch_code, ["result"], check_value=False)


def test_case_5():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        x = torch.randn(1, 2, 10)
        model = nn.Linear(in_features=10, out_features=20, bias=True, dtype=torch.float32, device="cpu")
        result = model(x)
        """
    )
    obj.run(pytorch_code, ["result"], check_value=False)


# generated by validate_unittest autofix, based on test_case_5
def test_case_6():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        x = torch.randn(1, 2, 10)
        model = nn.Linear(10, 20, True, "cpu", torch.float32)
        result = model(x)
        """
    )
    obj.run(pytorch_code, ["result"], check_value=False)


# generated by validate_unittest autofix, based on test_case_5
def test_case_7():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        x = torch.randn(1, 2, 10)
        model = nn.Linear(in_features=10, out_features=20, bias=True, device="cpu", dtype=torch.float32)
        result = model(x)
        """
    )
    obj.run(pytorch_code, ["result"], check_value=False)


def test_case_8():
    pytorch_code = textwrap.dedent(
        """
        import torch
        x = torch.randn(1, 2, 10).to(torch.float64)
        model = torch.nn.Linear(10, 20, bias=True, dtype=torch.float64)
        result = model(x)
        """
    )
    obj.run(pytorch_code, ["result"], check_value=False)


def test_case_9():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        x = torch.randn(1, 5, 7).to(torch.float16)
        model = nn.Linear(out_features=11, in_features=7, bias=False, dtype=torch.float16)
        result = model(x)
        """
    )
    obj.run(pytorch_code, ["result"], check_value=False)


# generated by validate_unittest autofix, based on test_case_7
def test_case_10():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        x = torch.randn(1, 2, 9).to(torch.float32)
        model = nn.Linear(9, out_features=20, bias=True, device="cpu", dtype=torch.float32)
        result = model(x)
        """
    )
    obj.run(pytorch_code, ["result"], check_value=False)


def test_case_11():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        x = torch.randn(2, 2, 8).to(torch.float32)
        x.requires_grad=True
        model = nn.Linear(8, out_features=20, bias=True, device="cpu", dtype=torch.float32)
        result = model(x)
        loss = result.mean()
        loss.backward()
        x_grad = x.grad
        x_grad.requires_grad=False
        """
    )
    obj.run(pytorch_code, ["result", "x_grad"], check_value=False)


def test_case_12():
    pytorch_code = textwrap.dedent(
        """
        import torch
        x = torch.randn(2, 14, 33)
        x.requires_grad=True
        model = torch.nn.Linear(33, out_features=20, bias=False, device=x.device, dtype=x.dtype)
        result = model(x)
        loss = result.sum()
        loss.backward()
        x_grad = x.grad
        x_grad.requires_grad=False
        """
    )
    obj.run(pytorch_code, ["result", "x_grad"], check_value=False)
