# Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import textwrap

from apibase import APIBase

obj = APIBase("torch.nn.MaxUnpool3d")


def test_case_1():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        pool = nn.MaxPool3d(3, stride=2, return_indices=True)
        unpool = nn.MaxUnpool3d(3, stride=2)
        output, indices = pool(torch.ones(2, 16, 51, 33, 15))
        result = unpool(output, indices)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_2():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        pool = nn.MaxPool3d(3, stride=2, return_indices=True)
        unpool = nn.MaxUnpool3d(3, 2)
        output, indices = pool(torch.ones(2, 16, 51, 33, 15))
        result = unpool(output, indices)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_3():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        pool = nn.MaxPool3d(3, stride=2, return_indices=True)
        unpool = nn.MaxUnpool3d(3, stride=2, padding=0)
        output, indices = pool(torch.ones(2, 16, 51, 33, 15))
        result = unpool(output, indices)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_4():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        pool = nn.MaxPool3d(3, stride=2, return_indices=True)
        unpool = nn.MaxUnpool3d(3, 2, padding=0)
        output, indices = pool(torch.ones(2, 16, 51, 33, 15))
        result = unpool(output, indices)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_5():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        pool = nn.MaxPool3d(3, stride=2, return_indices=True)
        unpool = nn.MaxUnpool3d(3, 2, 0)
        output, indices = pool(torch.ones(2, 16, 51, 33, 15))
        result = unpool(output, indices)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_6():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        pool = nn.MaxPool3d(3, stride=2, return_indices=True)
        unpool = nn.MaxUnpool3d(3, stride=None, padding=0)
        output, indices = pool(torch.ones(2, 16, 51, 33, 15))
        result = unpool(output, indices)
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_3
def test_case_7():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        pool = nn.MaxPool3d(3, stride=2, return_indices=True)
        unpool = nn.MaxUnpool3d(kernel_size=3, stride=2, padding=0)
        output, indices = pool(torch.ones(2, 16, 51, 33, 15))
        result = unpool(output, indices)
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_3
def test_case_8():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        pool = nn.MaxPool3d(3, stride=2, return_indices=True)
        unpool = nn.MaxUnpool3d(padding=0, stride=2, kernel_size=3)
        output, indices = pool(torch.ones(2, 16, 51, 33, 15))
        result = unpool(output, indices)
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_3
def test_case_9():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        pool = nn.MaxPool3d(3, stride=2, return_indices=True)
        unpool = nn.MaxUnpool3d(3)
        output, indices = pool(torch.ones(2, 16, 51, 33, 15))
        result = unpool(output, indices)
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_4
def test_case_10():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        pool = nn.MaxPool3d(3, stride=2, return_indices=True)
        unpool = nn.MaxUnpool3d(kernel_size=3, stride=2, padding=0)
        output, indices = pool(torch.ones(2, 16, 51, 33, 15))
        result = unpool(output, indices)
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_4
def test_case_11():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        pool = nn.MaxPool3d(3, stride=2, return_indices=True)
        unpool = nn.MaxUnpool3d(padding=0, stride=2, kernel_size=3)
        output, indices = pool(torch.ones(2, 16, 51, 33, 15))
        result = unpool(output, indices)
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_4
def test_case_12():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        pool = nn.MaxPool3d(3, stride=2, return_indices=True)
        unpool = nn.MaxUnpool3d(3)
        output, indices = pool(torch.ones(2, 16, 51, 33, 15))
        result = unpool(output, indices)
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_5
def test_case_13():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        pool = nn.MaxPool3d(3, stride=2, return_indices=True)
        unpool = nn.MaxUnpool3d(kernel_size=3, stride=2, padding=0)
        output, indices = pool(torch.ones(2, 16, 51, 33, 15))
        result = unpool(output, indices)
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_5
def test_case_14():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        pool = nn.MaxPool3d(3, stride=2, return_indices=True)
        unpool = nn.MaxUnpool3d(padding=0, stride=2, kernel_size=3)
        output, indices = pool(torch.ones(2, 16, 51, 33, 15))
        result = unpool(output, indices)
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_5
def test_case_15():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        pool = nn.MaxPool3d(3, stride=2, return_indices=True)
        unpool = nn.MaxUnpool3d(3)
        output, indices = pool(torch.ones(2, 16, 51, 33, 15))
        result = unpool(output, indices)
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_6
def test_case_16():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        pool = nn.MaxPool3d(3, stride=2, return_indices=True)
        unpool = nn.MaxUnpool3d(kernel_size=3, stride=None, padding=0)
        output, indices = pool(torch.ones(2, 16, 51, 33, 15))
        result = unpool(output, indices)
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_6
def test_case_17():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        pool = nn.MaxPool3d(3, stride=2, return_indices=True)
        unpool = nn.MaxUnpool3d(padding=0, stride=None, kernel_size=3)
        output, indices = pool(torch.ones(2, 16, 51, 33, 15))
        result = unpool(output, indices)
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_6
def test_case_18():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        pool = nn.MaxPool3d(3, stride=2, return_indices=True)
        unpool = nn.MaxUnpool3d(3)
        output, indices = pool(torch.ones(2, 16, 51, 33, 15))
        result = unpool(output, indices)
        """
    )
    obj.run(pytorch_code, ["result"])
