# Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import textwrap

from apibase import APIBase

obj = APIBase("torch.mm")


def test_case_1():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([[1., 2.], [4., 5.]])
        b = torch.tensor([[1., 3.], [3., 6.]])
        result = torch.mm(a, b)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_2():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([[1., 2.], [4., 5.]])
        b = torch.tensor([[1., 3.], [3., 6.]])
        result = torch.mm(input=a, mat2=b)
        """
    )
    obj.run(pytorch_code, ["result"])


# The paddle input does not support integer type
def _test_case_3():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([[1, 2], [4, 5]])
        b = torch.tensor([[1, 3], [3, 6]])
        result = torch.mm(a, b)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_4():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([[1., 2.], [4., 5.]])
        b = torch.tensor([[1., 3.], [3., 6.]])
        out = torch.tensor([[1., 2.], [4., 5.]])
        result = torch.mm(a, b, out=out)
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_4
def test_case_5():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([[1., 2.], [4., 5.]])
        b = torch.tensor([[1., 3.], [3., 6.]])
        out = torch.tensor([[1., 2.], [4., 5.]])
        result = torch.mm(input=a, mat2=b, out=out)
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_4
def test_case_6():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([[1., 2.], [4., 5.]])
        b = torch.tensor([[1., 3.], [3., 6.]])
        out = torch.tensor([[1., 2.], [4., 5.]])
        result = torch.mm(out=out, mat2=b, input=a)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_7():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([[1., 2., 3.], [4., 5., 6.]])
        b = torch.tensor([[1., 2.], [3., 4.], [5., 6.]])
        result = torch.mm(a, b)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_8():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([[1., 2., 3.], [4., 5., 6.]])
        b = torch.tensor([[1., 2.], [3., 4.], [5., 6.]])
        result = torch.mm(input=a, mat2=b)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_9():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([[1., 2.], [3., 4.], [5., 6.]])
        b = torch.tensor([[1., 2., 3., 4.], [5., 6., 7., 8.]])
        result = torch.mm(a, b)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_10():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([[1., 2.], [4., 5.]], dtype=torch.float64)
        b = torch.tensor([[1., 3.], [3., 6.]], dtype=torch.float64)
        result = torch.mm(a, b)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_11():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]])
        b = torch.tensor([[9., 8., 7.], [6., 5., 4.], [3., 2., 1.]])
        result = torch.mm(a, b)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_12():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([[1., 2.], [4., 5.]])
        b = torch.tensor([[1., 3.], [3., 6.]])
        args = (a, b)
        result = torch.mm(*args)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_13():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([[1., 2.], [4., 5.]], requires_grad=True)
        b = torch.tensor([[1., 3.], [3., 6.]], requires_grad=True)
        result = torch.mm(a, b)
        """
    )
    obj.run(pytorch_code, ["result"], check_stop_gradient=False)


# Paddle leaf tensor .grad returns None in exec() context, framework mechanism difference
def _test_case_14():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([[1., 2.], [4., 5.]], requires_grad=True)
        b = torch.tensor([[1., 3.], [3., 6.]], requires_grad=True)
        result = torch.mm(a, b)
        result.sum().backward()
        a_grad = a.grad
        b_grad = b.grad
        """
    )
    obj.run(pytorch_code, ["result", "a_grad", "b_grad"], check_stop_gradient=False)
