# Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

import textwrap

from apibase import APIBase

obj = APIBase("torch.bitwise_not")


def test_case_1():
    pytorch_code = textwrap.dedent(
        """
        import torch
        result = torch.bitwise_not(torch.tensor([-1, -2, 3], dtype=torch.int8))
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_2():
    pytorch_code = textwrap.dedent(
        """
        import torch
        input = torch.tensor([-1, -2, 3], dtype=torch.int8)
        result = torch.bitwise_not(input)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_3():
    pytorch_code = textwrap.dedent(
        """
        import torch
        input = torch.tensor([True, False, True], dtype=torch.bool)
        result = torch.bitwise_not(input)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_4():
    pytorch_code = textwrap.dedent(
        """
        import torch
        input = torch.tensor([-1, -2, 3], dtype=torch.int8)
        out = torch.tensor(input)
        result = torch.bitwise_not(input, out=out)
        """
    )
    obj.run(pytorch_code, ["result", "out"])


# generated by validate_unittest autofix, based on test_case_4
def test_case_5():
    pytorch_code = textwrap.dedent(
        """
        import torch
        input = torch.tensor([-1, -2, 3], dtype=torch.int8)
        out = torch.tensor(input)
        result = torch.bitwise_not(input=input, out=out)
        """
    )
    obj.run(pytorch_code, ["result", "out"])


# generated by validate_unittest autofix, based on test_case_4
def test_case_6():
    pytorch_code = textwrap.dedent(
        """
        import torch
        input = torch.tensor([-1, -2, 3], dtype=torch.int8)
        out = torch.tensor(input)
        result = torch.bitwise_not(out=out, input=input)
        """
    )
    obj.run(pytorch_code, ["result", "out"])


def test_case_7():
    """测试不同数据类型：int16"""
    pytorch_code = textwrap.dedent(
        """
        import torch
        input = torch.tensor([15, 7, 3], dtype=torch.int16)
        result = torch.bitwise_not(input)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_8():
    """测试不同数据类型：int32"""
    pytorch_code = textwrap.dedent(
        """
        import torch
        input = torch.tensor([255, 127, 63], dtype=torch.int32)
        result = torch.bitwise_not(input)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_9():
    """测试不同数据类型：int64"""
    pytorch_code = textwrap.dedent(
        """
        import torch
        input = torch.tensor([1023, 511, 255], dtype=torch.int64)
        result = torch.bitwise_not(input)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_10():
    """测试不同维度：2D张量"""
    pytorch_code = textwrap.dedent(
        """
        import torch
        input = torch.tensor([[1, 2], [3, 4]], dtype=torch.int8)
        result = torch.bitwise_not(input)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_11():
    """测试不同维度：3D张量"""
    pytorch_code = textwrap.dedent(
        """
        import torch
        input = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]], dtype=torch.int8)
        result = torch.bitwise_not(input)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_12():
    """测试混合参数顺序"""
    pytorch_code = textwrap.dedent(
        """
        import torch
        result = torch.bitwise_not(input=torch.tensor([-1, -2, 3], dtype=torch.int8))
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_13():
    """测试变量传参"""
    pytorch_code = textwrap.dedent(
        """
        import torch
        input = torch.tensor([True, False, True])
        args = (input,)
        result = torch.bitwise_not(*args)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_14():
    """测试空张量"""
    pytorch_code = textwrap.dedent(
        """
        import torch
        input = torch.empty(0, dtype=torch.int8)
        result = torch.bitwise_not(input)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_15():
    """测试表达式参数"""
    pytorch_code = textwrap.dedent(
        """
        import torch
        input = torch.tensor([15, 7, 3], dtype=torch.int8)
        result = torch.bitwise_not(input + 1)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_16():
    """测试无符号整数类型"""
    pytorch_code = textwrap.dedent(
        """
        import torch
        input = torch.tensor([15, 7, 3], dtype=torch.uint8)
        result = torch.bitwise_not(input)
        """
    )
    obj.run(pytorch_code, ["result"])
