# Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import textwrap

from apibase import APIBase

obj = APIBase("torch.fft.ifft")


def test_case_1():
    pytorch_code = textwrap.dedent(
        """
        import torch
        t = torch.arange(5)
        result = torch.fft.ifft(t)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_2():
    pytorch_code = textwrap.dedent(
        """
        import torch
        t = torch.arange(5)
        result = torch.fft.ifft(input=t, n=2)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_3():
    pytorch_code = textwrap.dedent(
        """
        import torch
        t = torch.arange(9).reshape(3, 3)
        result = torch.fft.ifft(input=t, n=2, dim=1)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_4():
    pytorch_code = textwrap.dedent(
        """
        import torch
        t = torch.arange(5)
        result = torch.fft.ifft(t, norm="ortho")
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_5():
    pytorch_code = textwrap.dedent(
        """
        import torch
        t = torch.arange(5)
        result = torch.fft.ifft(t, norm="backward")
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_6():
    pytorch_code = textwrap.dedent(
        """
        import torch
        t = torch.arange(5)
        result = torch.fft.ifft(t, norm="forward")
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_7():
    pytorch_code = textwrap.dedent(
        """
        import torch
        t = torch.arange(9).reshape(3, 3)
        out = torch.complex(torch.randn(3, 2), torch.randn(3, 2))
        result = torch.fft.ifft(t, n=2, dim=1, norm="forward", out=out)
        """
    )
    obj.run(pytorch_code, ["result", "out"])


# generated by validate_unittest autofix, based on test_case_7
def test_case_8():
    pytorch_code = textwrap.dedent(
        """
        import torch
        t = torch.arange(9).reshape(3, 3)
        result = torch.fft.ifft(t, 2, 1, "forward")
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_7
def test_case_9():
    pytorch_code = textwrap.dedent(
        """
        import torch
        t = torch.arange(9).reshape(3, 3)
        out = torch.complex(torch.randn(3, 2), torch.randn(3, 2))
        result = torch.fft.ifft(input=t, n=2, dim=1, norm="forward", out=out)
        """
    )
    obj.run(pytorch_code, ["result", "out"])


# generated by validate_unittest autofix, based on test_case_7
def test_case_10():
    pytorch_code = textwrap.dedent(
        """
        import torch
        t = torch.arange(9).reshape(3, 3)
        out = torch.complex(torch.randn(3, 2), torch.randn(3, 2))
        result = torch.fft.ifft(out=out, norm="forward", dim=1, n=2, input=t)
        """
    )
    obj.run(pytorch_code, ["result", "out"])
