# Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import textwrap

import paddle
import pytest
from apibase import APIBase

obj = APIBase("torch.nn.Conv1d")


def test_case_1():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        x = torch.randn(20, 16, 50)
        model = nn.Conv1d(16, 33, 3, stride=2, bias=False)
        result = model(x)
        """
    )
    obj.run(pytorch_code, ["result"], check_value=False)


def test_case_2():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        x = torch.randn(20, 16, 50)
        model = nn.Conv1d(16, 33, 3, stride=2, padding=4, bias=False)
        result = model(x)
        """
    )
    obj.run(pytorch_code, ["result"], check_value=False)


def test_case_3():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        x = torch.randn(20, 16, 50)
        model = nn.Conv1d(16, 33,  5, stride=2, padding=2, dilation=1, bias=False)
        result = model(x)
        """
    )
    obj.run(pytorch_code, ["result"], check_value=False)


def test_case_4():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        x = torch.randn(5, 16, 50)
        model = nn.Conv1d(16, 33, 5, stride=1, padding=4, dilation=3, bias=True)
        result = model(x)
        """
    )
    obj.run(pytorch_code, ["result"], check_value=False)


def test_case_5():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        x = torch.randn(5, 16, 50)
        model = nn.Conv1d(16, 33, 5, stride=1, padding=4, dilation=3, bias=True, padding_mode='zeros')
        result = model(x)
        """
    )
    obj.run(pytorch_code, ["result"], check_value=False)


def test_case_6():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        x = torch.randn(5, 16, 50)
        model = nn.Conv1d(16, 33, 5, stride=1, padding=4, dilation=3, groups=1, bias=True, padding_mode='zeros', device='cpu', dtype=torch.float32)
        result = model(x)
        """
    )
    obj.run(pytorch_code, ["result"], check_value=False)


# generated by validate_unittest autofix, based on test_case_6
def test_case_7():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        x = torch.randn(5, 16, 50)
        model = nn.Conv1d(16, 33, 5, 1, 4, 3, 1, bias=True, padding_mode='zeros', device='cpu', dtype=torch.float32)
        result = model(x)
        """
    )
    obj.run(pytorch_code, ["result"], check_value=False)


# generated by validate_unittest autofix, based on test_case_6
def test_case_8():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        x = torch.randn(5, 16, 50)
        model = nn.Conv1d(in_channels=16, out_channels=33, kernel_size=5, stride=1, padding=4, dilation=3, groups=1, bias=True, padding_mode='zeros', device='cpu', dtype=torch.float32)
        result = model(x)
        """
    )
    obj.run(pytorch_code, ["result"], check_value=False)


# generated by validate_unittest autofix, based on test_case_6
def test_case_9():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        x = torch.randn(5, 16, 50)
        model = nn.Conv1d(dtype=torch.float32, device='cpu', padding_mode='zeros', bias=True, groups=1, dilation=3, padding=4, stride=1, kernel_size=5, out_channels=33, in_channels=16)
        result = model(x)
        """
    )
    obj.run(pytorch_code, ["result"], check_value=False)


# generated by validate_unittest autofix, based on test_case_6
def test_case_10():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        x = torch.randn(5, 16, 50)
        model = nn.Conv1d(16, 33, 5)
        result = model(x)
        """
    )
    obj.run(pytorch_code, ["result"], check_value=False)


@pytest.mark.skipif(
    condition=not paddle.device.is_compiled_with_cuda(),
    reason="can only run on paddle with CUDA",
)
def test_case_11():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        x = torch.randn(5, 16, 50).to(torch.device('cuda:0'))
        model = nn.Conv1d(16, 33, 5, 1, 4, 3, 1, bias=True, padding_mode='zeros', device=torch.device('cuda:0'), dtype=torch.float32)
        result = model(x)
        """
    )
    obj.run(pytorch_code, ["result"], check_value=False)


def test_case_12():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        x = torch.randn(5, 16, 50)
        model = nn.Conv1d(16, 33, 5, 1, 4, 3, 1, bias=False, padding_mode='zeros', device='cpu', dtype=torch.float32)
        result = model(x)
        """
    )
    obj.run(pytorch_code, ["result"], check_value=False)


def test_case_13():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        x = torch.randn(5, 16, 50)
        model = nn.Conv1d(16, 33, 5, 1, 4, 3, 1, bias=False, padding_mode='zeros', device=('cpu'), dtype=torch.float32)
        result = model(input=x)
        """
    )
    obj.run(pytorch_code, ["result"], check_value=False)


def test_case_14():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        x = torch.randn(5, 16, 50).to(torch.float64)
        model = nn.Conv1d(16, 33, 5, 1, 4, 3, 1, bias=False, padding_mode='zeros', device=('cpu'), dtype=torch.float64)
        result = model(input=x)
        """
    )
    obj.run(pytorch_code, ["result"], check_value=False)
