# Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

import textwrap

from apibase import APIBase

obj = APIBase("torch.nextafter")


def test_case_1():
    pytorch_code = textwrap.dedent(
        """
        import torch
        result = torch.nextafter(torch.tensor([1.0, 2.0]), torch.tensor([2.0, 1.0]))
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_2():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([1.0, 2.0])
        b = torch.tensor([2.0, 1.0])
        result = torch.nextafter(a, b)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_3():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = [1.0, 2.0]
        b = [2.0, 1.0]
        out = torch.tensor(a)
        result = torch.nextafter(torch.tensor(a), torch.tensor(b), out=out)
        """
    )
    obj.run(pytorch_code, ["result", "out"])


# generated by validate_unittest autofix, based on test_case_3
def test_case_4():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = [1.0, 2.0]
        b = [2.0, 1.0]
        out = torch.tensor(a)
        result = torch.nextafter(input=torch.tensor(a), other=torch.tensor(b), out=out)
        """
    )
    obj.run(pytorch_code, ["result", "out"])


# generated by validate_unittest autofix, based on test_case_3
def test_case_5():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = [1.0, 2.0]
        b = [2.0, 1.0]
        out = torch.tensor(a)
        result = torch.nextafter(out=out, other=torch.tensor(b), input=torch.tensor(a))
        """
    )
    obj.run(pytorch_code, ["result", "out"])
