# Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import textwrap

from apibase import APIBase

obj = APIBase("torch.distributions.ReshapeTransform")


def test_case_1():
    pytorch_code = textwrap.dedent(
        """
        import torch

        reshape_transform = torch.distributions.ReshapeTransform((2, 3), (3, 2), cache_size=1)
        result = reshape_transform.forward_shape((1,2,3))
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_1
def test_case_2():
    pytorch_code = textwrap.dedent(
        """
        import torch

        reshape_transform = torch.distributions.ReshapeTransform((2, 3), (3, 2), 1)
        result = reshape_transform.forward_shape((1,2,3))
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_1
def test_case_3():
    pytorch_code = textwrap.dedent(
        """
        import torch

        reshape_transform = torch.distributions.ReshapeTransform(in_shape=(2, 3), out_shape=(3, 2), cache_size=1)
        result = reshape_transform.forward_shape((1,2,3))
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_1
def test_case_4():
    pytorch_code = textwrap.dedent(
        """
        import torch

        reshape_transform = torch.distributions.ReshapeTransform(cache_size=1, out_shape=(3, 2), in_shape=(2, 3))
        result = reshape_transform.forward_shape((1,2,3))
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_1
def test_case_5():
    pytorch_code = textwrap.dedent(
        """
        import torch

        reshape_transform = torch.distributions.ReshapeTransform((2, 3), (3, 2))
        result = reshape_transform.forward_shape((1,2,3))
        """
    )
    obj.run(pytorch_code, ["result"])
