# Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
import textwrap

from apibase import APIBase

obj = APIBase("torch.is_nonzero")


def test_case_1():
    pytorch_code = textwrap.dedent(
        """
        import torch
        result = torch.is_nonzero(torch.tensor([0.]))
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_2():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([1])
        result = torch.is_nonzero(a)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_3():
    pytorch_code = textwrap.dedent(
        """
        import torch
        result = torch.is_nonzero(torch.tensor([False]))
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_4():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = [0]
        b = torch.tensor(a)
        result = torch.is_nonzero(b)
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_1
def test_case_5():
    pytorch_code = textwrap.dedent(
        """
        import torch
        result = torch.is_nonzero(input=torch.tensor([0.]))
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_2
def test_case_6():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([1])
        result = torch.is_nonzero(input=a)
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_3
def test_case_7():
    pytorch_code = textwrap.dedent(
        """
        import torch
        result = torch.is_nonzero(input=torch.tensor([False]))
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_4
def test_case_8():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = [0]
        b = torch.tensor(a)
        result = torch.is_nonzero(input=b)
        """
    )
    obj.run(pytorch_code, ["result"])
