# Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

import textwrap

from apibase import APIBase

obj = APIBase("torch.split")


def test_case_1():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.arange(12).reshape(6, 2)
        result = torch.split(a, 2)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_2():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.arange(12).reshape(6, 2)
        result = torch.split(a, 2, dim=0)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_3():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.arange(12).reshape(6, 2)
        result = torch.split(a, 2, dim=1)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_4():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.arange(10).reshape(5, 2)
        result = torch.split(a, [1, 4])
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_5():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.arange(9).reshape(3, 3)
        result = torch.split(a, split_size_or_sections=[1, 2], dim=1)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_6():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.arange(12).reshape(6, 2)
        split_size = 2
        result = torch.split(a, split_size, dim=0)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_7():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.arange(10).reshape(5, 2)
        sections = [1, 4]
        result = torch.split(a, sections)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_8():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.arange(9).reshape(3,3)
        sections = [1, 2]
        result = torch.split(a, split_size_or_sections=sections, dim=1)
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_2
def test_case_9():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.arange(12).reshape(6, 2)
        result = torch.split(a, 2, 0)
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_2
def test_case_10():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.arange(12).reshape(6, 2)
        result = torch.split(tensor=a, split_size_or_sections=2, dim=0)
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_2
def test_case_11():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.arange(12).reshape(6, 2)
        result = torch.split(dim=0, split_size_or_sections=2, tensor=a)
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_3
def test_case_12():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.arange(12).reshape(6, 2)
        result = torch.split(a, 2, 1)
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_3
def test_case_13():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.arange(12).reshape(6, 2)
        result = torch.split(tensor=a, split_size_or_sections=2, dim=1)
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_3
def test_case_14():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.arange(12).reshape(6, 2)
        result = torch.split(dim=1, split_size_or_sections=2, tensor=a)
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_5
def test_case_15():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.arange(9).reshape(3, 3)
        result = torch.split(a, [1, 2], 1)
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_5
def test_case_16():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.arange(9).reshape(3, 3)
        result = torch.split(tensor=a, split_size_or_sections=[1, 2], dim=1)
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_5
def test_case_17():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.arange(9).reshape(3, 3)
        result = torch.split(dim=1, split_size_or_sections=[1, 2], tensor=a)
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_6
def test_case_18():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.arange(12).reshape(6, 2)
        split_size = 2
        result = torch.split(a, split_size, 0)
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_6
def test_case_19():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.arange(12).reshape(6, 2)
        split_size = 2
        result = torch.split(tensor=a, split_size_or_sections=split_size, dim=0)
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_6
def test_case_20():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.arange(12).reshape(6, 2)
        split_size = 2
        result = torch.split(dim=0, split_size_or_sections=split_size, tensor=a)
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_8
def test_case_21():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.arange(9).reshape(3,3)
        sections = [1, 2]
        result = torch.split(a, sections, 1)
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_8
def test_case_22():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.arange(9).reshape(3,3)
        sections = [1, 2]
        result = torch.split(tensor=a, split_size_or_sections=sections, dim=1)
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_8
def test_case_23():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.arange(9).reshape(3,3)
        sections = [1, 2]
        result = torch.split(dim=1, split_size_or_sections=sections, tensor=a)
        """
    )
    obj.run(pytorch_code, ["result"])

# Test unevenly split 1
def test_case_24():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.arange(54).reshape(3, 9, 2)
        split_size = 2
        result = torch.split(a, split_size, dim = 1)
        """
    )
    obj.run(pytorch_code, ["result"])

# Test unevenly split 2 with zero-shape
def test_case_25():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.arange(48).reshape(12, 1, 4)
        result = torch.split(a, split_size_or_sections=[5, 0, 7])
        """
    )
    obj.run(pytorch_code, ["result"])

# Test unevenly split 2 with negative-dim
def test_case_26():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.arange(48).reshape(4, 1, 12)
        result = torch.split(a, split_size_or_sections=[2, 5, 5], dim=-1)
        """
    )
    obj.run(pytorch_code, ["result"])
