# Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import textwrap

from apibase import APIBase

obj = APIBase("torch.nn.modules.batchnorm._BatchNorm")


def test_case_1():
    pytorch_code = textwrap.dedent(
        """
        import torch
        model = torch.nn.modules.batchnorm._BatchNorm(num_features=1)
        result = isinstance(model, torch.nn.Module)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_2():
    pytorch_code = textwrap.dedent(
        """
        import torch
        model = torch.nn.modules.batchnorm._BatchNorm(1, 1e-8, 0.1, True, True)
        result = isinstance(model, torch.nn.Module)
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_2
def test_case_3():
    pytorch_code = textwrap.dedent(
        """
        import torch
        model = torch.nn.modules.batchnorm._BatchNorm(1, 1e-8, 0.1, True, True, 'cpu', torch.float32)
        result = isinstance(model, torch.nn.Module)
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_2
def test_case_4():
    pytorch_code = textwrap.dedent(
        """
        import torch
        model = torch.nn.modules.batchnorm._BatchNorm(num_features=1, eps=1e-8, momentum=0.1, affine=True, track_running_stats=True, device='cpu', dtype=torch.float32)
        result = isinstance(model, torch.nn.Module)
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_2
def test_case_5():
    pytorch_code = textwrap.dedent(
        """
        import torch
        model = torch.nn.modules.batchnorm._BatchNorm(dtype=torch.float32, device='cpu', track_running_stats=True, affine=True, momentum=0.1, eps=1e-8, num_features=1)
        result = isinstance(model, torch.nn.Module)
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_2
def test_case_6():
    pytorch_code = textwrap.dedent(
        """
        import torch
        model = torch.nn.modules.batchnorm._BatchNorm(1)
        result = isinstance(model, torch.nn.Module)
        """
    )
    obj.run(pytorch_code, ["result"])
