# Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import textwrap

from apibase import APIBase

obj = APIBase("torch.lcm")


def test_case_1():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([5, 10, 15])
        b = torch.tensor([3, 4, 5])
        result = torch.lcm(a, b)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_2():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([5, 10, 15])
        b = torch.tensor([3, 4, 5])
        result = torch.lcm(input=a, other=b)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_3():
    pytorch_code = textwrap.dedent(
        """
        import torch
        result = torch.lcm(torch.tensor([5, 10, 15]), torch.tensor([3, 4, 5]))
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_4():
    pytorch_code = textwrap.dedent(
        """
        import torch
        result = torch.lcm(input=torch.tensor([5, 10, 15]), other=torch.tensor([3, 4, 5]))
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_5():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([5, 10, 15])
        b = torch.tensor([3, 4, 5])
        out = torch.tensor([3, 4, 5])
        result = torch.lcm(input=a, other=b, out=out)
        """
    )
    obj.run(pytorch_code, ["result", "out"])


def test_case_6():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([5, 10, 15])
        b = torch.tensor([3])
        result = torch.lcm(input=a, other=b)
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_5
def test_case_7():
    pytorch_code = textwrap.dedent(
        """
        import torch
        a = torch.tensor([5, 10, 15])
        b = torch.tensor([3, 4, 5])
        out = torch.tensor([3, 4, 5])
        result = torch.lcm(out=out, other=b, input=a)
        """
    )
    obj.run(pytorch_code, ["result", "out"])
