# Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import textwrap

from apibase import APIBase

obj = APIBase("torch.nn.BCELoss")


def test_case_1():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        input = torch.tensor([[0.2837, 0.0297,  0.0355],
            [ 0.9112, 0.7526, 0.4061]])
        target = torch.tensor([[1.,0.,1.],[0.,1.,0.]])
        weight = torch.tensor([0.5,0.2,0.3])
        loss = torch.nn.BCELoss(weight=weight,size_average=True)
        result = loss(input,target)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_2():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        input = torch.tensor([[0.2837, 0.0297,  0.0355],
            [ 0.9112, 0.7526, 0.4061]])
        target = torch.tensor([[1.,0.,1.],[0.,1.,0.]])
        weight = torch.tensor([0.5,0.2,0.3])
        loss = torch.nn.BCELoss(weight=weight,size_average=False)
        result = loss(input,target)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_3():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        input = torch.tensor([[0.2837, 0.0297,  0.0355],
            [ 0.9112, 0.7526, 0.4061]])
        target = torch.tensor([[1.,0.,1.],[0.,1.,0.]])
        weight = torch.tensor([0.5,0.2,0.3])
        loss = torch.nn.BCELoss(weight=weight,reduction='none')
        result = loss(input,target)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_4():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        input = torch.tensor([[0.2837, 0.0297,  0.0355],
            [ 0.9112, 0.7526, 0.4061]])
        target = torch.tensor([[1.,0.,1.],[0.,1.,0.]])
        weight = torch.tensor([0.5,0.2,0.3])
        loss = torch.nn.BCELoss(weight=weight,reduction='mean')
        result = loss(input,target)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_5():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        input = torch.tensor([[0.2837, 0.0297,  0.0355],
            [ 0.9112, 0.7526, 0.4061]])
        target = torch.tensor([[1.,0.,1.],[0.,1.,0.]])
        weight = torch.tensor([0.5,0.2,0.3])
        loss = torch.nn.BCELoss(weight=weight,reduction='sum')
        result = loss(input,target)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_6():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        input = torch.tensor([[0.2837, 0.0297,  0.0355],
            [ 0.9112, 0.7526, 0.4061]])
        target = torch.tensor([[1.,0.,1.],[0.,1.,0.]])
        weight = torch.tensor([0.5,0.2,0.3])
        loss = torch.nn.BCELoss(weight=weight,reduce=True)
        result = loss(input,target)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_7():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        input = torch.tensor([[0.2837, 0.0297,  0.0355],
            [ 0.9112, 0.7526, 0.4061]])
        target = torch.tensor([[1.,0.,1.],[0.,1.,0.]])
        weight = torch.tensor([0.5,0.2,0.3])
        loss = torch.nn.BCELoss(weight=weight,reduce=False)
        result = loss(input,target)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_8():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        input = torch.tensor([[0.2837, 0.0297,  0.0355],
            [ 0.9112, 0.7526, 0.4061]])
        target = torch.tensor([[1.,0.,1.],[0.,1.,0.]])
        loss = torch.nn.BCELoss()
        result = loss(input,target)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_9():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        input = torch.tensor([[0.2837, 0.0297,  0.0355],
            [ 0.9112, 0.7526, 0.4061]])
        target = torch.tensor([[1.,0.,1.],[0.,1.,0.]])
        weight = torch.tensor([0.5,0.2,0.3])
        loss = torch.nn.BCELoss(weight=weight, size_average=None, reduce=False, reduction='mean')
        result = loss(input,target)
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_9
def test_case_10():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        input = torch.tensor([[0.2837, 0.0297,  0.0355],
            [ 0.9112, 0.7526, 0.4061]])
        target = torch.tensor([[1.,0.,1.],[0.,1.,0.]])
        weight = torch.tensor([0.5,0.2,0.3])
        loss = torch.nn.BCELoss(weight, None, False, 'mean')
        result = loss(input,target)
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_9
def test_case_11():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        input = torch.tensor([[0.2837, 0.0297,  0.0355],
            [ 0.9112, 0.7526, 0.4061]])
        target = torch.tensor([[1.,0.,1.],[0.,1.,0.]])
        weight = torch.tensor([0.5,0.2,0.3])
        loss = torch.nn.BCELoss(reduction='mean', reduce=False, size_average=None, weight=weight)
        result = loss(input,target)
        """
    )
    obj.run(pytorch_code, ["result"])
