# Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import textwrap

from apibase import APIBase

obj = APIBase("torch.nn.functional.triplet_margin_with_distance_loss")


def test_case_1():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        import numpy as np
        np.random.seed(100)
        anchor = torch.tensor(np.random.rand(128))
        positive = torch.tensor(np.random.rand(128))
        negative = torch.tensor(np.random.rand(128))
        result = nn.functional.triplet_margin_with_distance_loss(anchor, positive, negative, distance_function=nn.PairwiseDistance())
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_2():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        import numpy as np
        np.random.seed(100)
        anchor = torch.tensor(np.random.rand(128))
        positive = torch.tensor(np.random.rand(128))
        negative = torch.tensor(np.random.rand(128))
        result = torch.nn.functional.triplet_margin_with_distance_loss(anchor=anchor, positive=positive, negative=negative, distance_function=nn.PairwiseDistance(), margin=2.0, reduction='mean')
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_3():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        import numpy as np
        np.random.seed(100)
        anchor = torch.tensor(np.random.rand(128))
        positive = torch.tensor(np.random.rand(128))
        negative = torch.tensor(np.random.rand(128))
        result = torch.nn.functional.triplet_margin_with_distance_loss(anchor, positive, negative, distance_function=nn.PairwiseDistance(), margin=2.0, swap=True, reduction='none')
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_3
def test_case_4():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        import numpy as np
        np.random.seed(100)
        anchor = torch.tensor(np.random.rand(128))
        positive = torch.tensor(np.random.rand(128))
        negative = torch.tensor(np.random.rand(128))
        result = torch.nn.functional.triplet_margin_with_distance_loss(anchor=anchor, positive=positive, negative=negative, distance_function=nn.PairwiseDistance(), margin=2.0, swap=True, reduction='none')
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_3
def test_case_5():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        import numpy as np
        np.random.seed(100)
        anchor = torch.tensor(np.random.rand(128))
        positive = torch.tensor(np.random.rand(128))
        negative = torch.tensor(np.random.rand(128))
        result = torch.nn.functional.triplet_margin_with_distance_loss(reduction='none', swap=True, margin=2.0, distance_function=nn.PairwiseDistance(), negative=negative, positive=positive, anchor=anchor)
        """
    )
    obj.run(pytorch_code, ["result"])


# generated by validate_unittest autofix, based on test_case_3
def test_case_6():
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        import numpy as np
        np.random.seed(100)
        anchor = torch.tensor(np.random.rand(128))
        positive = torch.tensor(np.random.rand(128))
        negative = torch.tensor(np.random.rand(128))
        result = torch.nn.functional.triplet_margin_with_distance_loss(anchor, positive, negative)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_7():
    """All keyword arguments with all options"""
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        import numpy as np
        np.random.seed(101)
        anchor = torch.tensor(np.random.rand(64, 32), dtype=torch.float32)
        positive = torch.tensor(np.random.rand(64, 32), dtype=torch.float32)
        negative = torch.tensor(np.random.rand(64, 32), dtype=torch.float32)
        result = torch.nn.functional.triplet_margin_with_distance_loss(
            anchor=anchor, positive=positive, negative=negative,
            distance_function=nn.PairwiseDistance(p=2),
            margin=1.5, swap=False, reduction='sum')
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_8():
    """Mixed positional and keyword arguments"""
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        import numpy as np
        np.random.seed(102)
        anchor = torch.tensor(np.random.rand(8, 16), dtype=torch.float32)
        positive = torch.tensor(np.random.rand(8, 16), dtype=torch.float32)
        negative = torch.tensor(np.random.rand(8, 16), dtype=torch.float32)
        result = torch.nn.functional.triplet_margin_with_distance_loss(
            anchor, positive, negative, margin=2.0, swap=True)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_9():
    """Default args omitted (no distance_function, all defaults)"""
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        import numpy as np
        np.random.seed(103)
        anchor = torch.tensor(np.random.rand(4, 8), dtype=torch.float32)
        positive = torch.tensor(np.random.rand(4, 8), dtype=torch.float32)
        negative = torch.tensor(np.random.rand(4, 8), dtype=torch.float32)
        result = torch.nn.functional.triplet_margin_with_distance_loss(
            anchor, positive, negative, reduction='none')
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_10():
    """Variable args unpacking"""
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        import numpy as np
        np.random.seed(104)
        anchor = torch.tensor(np.random.rand(16, 8), dtype=torch.float32)
        positive = torch.tensor(np.random.rand(16, 8), dtype=torch.float32)
        negative = torch.tensor(np.random.rand(16, 8), dtype=torch.float32)
        args = (anchor, positive, negative)
        result = torch.nn.functional.triplet_margin_with_distance_loss(*args, margin=1.0)
        """
    )
    obj.run(pytorch_code, ["result"])


def test_case_11():
    """float64 dtype"""
    pytorch_code = textwrap.dedent(
        """
        import torch
        import torch.nn as nn
        import numpy as np
        np.random.seed(105)
        anchor = torch.tensor(np.random.rand(8, 8), dtype=torch.float64)
        positive = torch.tensor(np.random.rand(8, 8), dtype=torch.float64)
        negative = torch.tensor(np.random.rand(8, 8), dtype=torch.float64)
        result = torch.nn.functional.triplet_margin_with_distance_loss(
            anchor, positive, negative, margin=0.5)
        """
    )
    obj.run(pytorch_code, ["result"])
