import paddle

print("#########################case1#########################")
cpu = paddle.device("cpu")
a = paddle.randn(2, 3)
c = paddle.randn(2, 3, dtype=paddle.float64, device=cpu)
b = a.to(cpu, non_blocking=False, copy=False)
print("#########################case2#########################")
b = a.to("cpu")
print("#########################case3#########################")
b = a.to(device=cpu, dtype=paddle.float64)
print("#########################case4#########################")
b = a.to(paddle.float64)
print("#########################case5#########################")
b = a.to(dtype=paddle.float64)
print("#########################case6#########################")
b = a.to(c)
print("#########################case7#########################")
a = a.to(paddle.float16)
print("#########################case8#########################")
table = a
b = a.to(table.device)
print("#########################case9#########################")
b = a.to(paddle.float32)
print("#########################case10#########################")
device = paddle.device("cpu")
b = paddle.tensor([-1]).to(paddle.bool)
print("#########################case11#########################")
dtype = paddle.float32
b = a.to(dtype=dtype)
print("#########################case12#########################")
b = a.to(paddle.device("cpu"))
