import torch
import copy
print('#########################case1#########################')
result = torch.BFloat16Tensor([1.5, 2, 3])
print('#########################case2#########################')
result = torch.BoolTensor(2, 3)
print('#########################case3#########################')
result = torch.ByteTensor(2, 3)
print('#########################case4#########################')
result = torch.CharTensor(2, 3)
print('#########################case5#########################')
result = torch.DoubleTensor(2, 3)
print('#########################case6#########################')
result = torch.FloatTensor(2, 3)
print('#########################case7#########################')
result = torch.Generator(device='cpu')
print('#########################case8#########################')
result = torch.HalfTensor(2, 3)
print('#########################case9#########################')
result = torch.IntTensor(2, 3)
print('#########################case10#########################')
result = torch.LongTensor(2, 3)
print('#########################case11#########################')
result = torch.ShortTensor(2, 3)
print('#########################case12#########################')
result = list(torch.Size([2, 8, 64, 64]))
print('#########################case13#########################')
result = torch.Tensor(2, 3)
print('#########################case14#########################')
x = torch.arange(16).reshape(4, 4)
result = x.T
print('#########################case15#########################')
x = torch.tensor([True, False, True])
y = torch.tensor([True, True, False])
result = x & y
print('#########################case16#########################')
x = torch.tensor([1.0, 2.0, 3.0])
result = x.__array__()
print('#########################case17#########################')
x = torch.tensor([True])
result = bool(x)
print('#########################case18#########################')
x = torch.tensor([True])
result = copy.deepcopy(x)
print('#########################case19#########################')
x = torch.tensor([1.0, 2.0, 3.0])
y = torch.tensor([1.0, 2.0, 3.0])
result = x == y
print('#########################case20#########################')
x = torch.tensor([2.0, 4.0])
result = 8 // x
print('#########################case21#########################')
x = torch.tensor([3.0, 2.0, 1.0])
y = torch.tensor([1.0, 2.0, 3.0])
result = x >= y
print('#########################case22#########################')
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = x[1, 2]
print('#########################case23#########################')
x = torch.tensor([3.0, 2.0, 1.0])
y = torch.tensor([1.0, 2.0, 3.0])
result = x > y
print('#########################case24#########################')
x = torch.tensor(5)
result = x.__index__()
print('#########################case25#########################')
x = torch.tensor(2.0)
result = int(x)
print('#########################case26#########################')
x = torch.tensor([True, False])
result = ~x
print('#########################case27#########################')
x = torch.tensor([True, False, True])
y = torch.tensor([True, True, False])
x |= y
print('#########################case28#########################')
x = torch.tensor([3.0, 2.0, 1.0])
y = torch.tensor([1.0, 2.0, 3.0])
result = x <= y
print('#########################case29#########################')
x = torch.tensor([1.0, 2.0, 3.0, 4.0])
result = len(x)
print('#########################case30#########################')
x = torch.tensor([3.0, 2.0, 1.0])
y = torch.tensor([1.0, 2.0, 3.0])
result = x < y
print('#########################case31#########################')
x = torch.tensor([3.0, 2.0, 1.0])
y = torch.tensor([1.0, 2.0, 3.0])
result = x != y
print('#########################case32#########################')
x = torch.tensor([1.0, 2.0], dtype=torch.float32)
result = -x
print('#########################case33#########################')
x = torch.tensor([1.0], dtype=torch.float32)
result = not x
print('#########################case34#########################')
x = torch.tensor([True, False, True])
y = torch.tensor([True, True, False])
result = x | y
print('#########################case35#########################')
x = torch.tensor([1, 2, 3], dtype=torch.int64)
result = 5 + x
print('#########################case36#########################')
x = torch.tensor([2.0, 3.0])
result = 5 - x
print('#########################case37#########################')
x = torch.tensor([2.0, 4.0])
result = 8 / x
print('#########################case38#########################')
x = torch.tensor([1.0, 2.0, 3.0])
x[1] = 5.0
result = x
print('#########################case39#########################')
x = torch.tensor([True, False, True])
y = torch.tensor([True, True, False])
result = x ^ y
print('#########################case40#########################')
a = torch.tensor([[-4, 9], [-23, 2]])
result = a.abs()
print('#########################case41#########################')
a = torch.tensor([-1])
a.abs_()
print('#########################case42#########################')
a = torch.tensor([0.34, -0.56, 0.73])
a.acos_()
print('#########################case43#########################')
result = torch.tensor([1.3192, 1.9915, 1.9674, 1.7151]).acosh()
print('#########################case44#########################')
result = torch.tensor([1.3192, 1.9915, 1.9674, 1.7151]).acosh_()
print('#########################case45#########################')
x = torch.tensor([1, 2, 3])
result = x.add(torch.tensor([1, 4, 6]))
print('#########################case46#########################')
x = torch.tensor([1, 2, 3])
x.add_(torch.tensor([1, 4, 6]))
print('#########################case47#########################')
a = torch.rand(1, 2).bool()
result = a.all()
print('#########################case48#########################')
x = torch.tensor([[1, 2, 3], [3, 4, 6]])
result = x.amax()
print('#########################case49#########################')
x = torch.tensor([[1, 2, 3], [3, 4, 6]])
result = x.amin()
print('#########################case50#########################')
a = torch.rand(1, 2).bool()
result = a.any()
print('#########################case51#########################')
x = torch.tensor([1.3192, 1.9915, 1.9674, 1.7151])
result = x.apply_(lambda x: x * 2)
print('#########################case52#########################')
x = torch.tensor([[1, 2, 3], [3, 4, 6]])
result = x.argmax()
print('#########################case53#########################')
x = torch.tensor([[1, 2, 3], [3, 4, 6]])
result = x.argmin()
print('#########################case54#########################')
result = torch.tensor([0.34, -0.56, 0.73]).asin()
print('#########################case55#########################')
result = torch.tensor([0.34, -0.56, 0.73]).asin_()
print('#########################case56#########################')
result = torch.tensor([0.34, -0.56, 0.73]).asinh_()
print('#########################case57#########################')
result = torch.tensor([0.34, -0.56, 0.73]).atan()
print('#########################case58#########################')
result = torch.tensor([0.34, -0.56, 0.73]).atan_()
print('#########################case59#########################')
result = torch.tensor([0.34, -0.56, 0.73]).atanh_()
print('#########################case60#########################')
x = torch.tensor([1, 2, 3])
y = torch.tensor([-1, 9, 10])
result = x.bitwise_and(y)
print('#########################case61#########################')
x = torch.tensor([1, 2, 3])
y = torch.tensor([-1, 9, 10])
x.bitwise_and_(y)
print('#########################case62#########################')
input = torch.tensor([-2, -7, 31], dtype=torch.int8)
other = torch.tensor([1, 0, 3], dtype=torch.int8)
result = input.bitwise_left_shift(other)
print('#########################case63#########################')
input = torch.tensor([-2, -7, 31], dtype=torch.int8)
other = torch.tensor([1, 0, 3], dtype=torch.int8)
result = input.bitwise_left_shift_(other)
print('#########################case64#########################')
x = torch.tensor([1, 2, 3])
result = x.bitwise_not()
print('#########################case65#########################')
x = torch.tensor([1, 2, 3])
x.bitwise_not_()
print('#########################case66#########################')
x = torch.tensor([1, 2, 3])
y = torch.tensor([-1, 9, 10])
result = x.bitwise_or(y)
print('#########################case67#########################')
x = torch.tensor([1, 2, 3])
y = torch.tensor([-1, 9, 10])
x.bitwise_or_(y)
print('#########################case68#########################')
input = torch.tensor([-2, -7, 31], dtype=torch.int8)
other = torch.tensor([1, 0, 3], dtype=torch.int8)
result = input.bitwise_right_shift(other)
print('#########################case69#########################')
input = torch.tensor([-2, -7, 31], dtype=torch.int8)
other = torch.tensor([1, 0, 3], dtype=torch.int8)
result = input.bitwise_right_shift_(other)
print('#########################case70#########################')
x = torch.tensor([1, 2, 3])
y = torch.tensor([-1, 9, 10])
result = x.bitwise_xor(y)
print('#########################case71#########################')
x = torch.tensor([1, 2, 3])
y = torch.tensor([-1, 9, 10])
x.bitwise_xor_(y)
print('#########################case72#########################')
x = torch.tensor([1, 2, 3])
result = x.broadcast_to((3, 3))
print('#########################case73#########################')
x = torch.randn([3, 4])
result = x.cauchy_()
print('#########################case74#########################')
a = torch.tensor([1.1, 2.5, 3.6, 4.8])
result = a.ceil()
print('#########################case75#########################')
a = torch.tensor([-1.712, 0.1734, -0.0478, 0.8922])
result = a.clamp(-0.5, 0.5)
print('#########################case76#########################')
x = torch.tensor([-1.712, 0.1734, -0.0478, -0.0922])
result = x.clip(-0.5, 0.5)
