# A image for testing PaConvert
FROM registry.baidubce.com/paddlepaddle/paddle:latest-dev-cuda11.8-cudnn8.6-trt8.5-gcc82

ENV PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple

RUN apt-get -o Acquire::Retries=5 update || true; \
    apt-get -o Acquire::Retries=5 install -y net-tools || true

RUN ln -sf `which python3.10` /usr/bin/python

RUN ln -sf `which pip3.10` /usr/local/bin/pip

RUN python -m pip install --no-cache-dir \
        astor \
        pandas \
        openpyxl \
        pytest-timeout \
        pytest-rerunfailures

RUN python -m pip install --no-cache-dir \
        torch==2.7.1 torchvision==0.22.1 \
        --index-url https://mirrors.aliyun.com/pytorch-wheels/cpu
